#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "Arial:Bold:12.0"
#spacebar -m config icon_font            "Font Awesome 5 Free:Solid:13.0"
spacebar -m config icon_font            "Hack Nerd Font:Regular:16.0"
spacebar -m config background_color     0xff202020
spacebar -m config foreground_color     0xffa8a8a8
#spacebar -m config space_icon_color     0xff458588
spacebar -m config space_icon_color     0xff11ccff
spacebar -m config power_icon_color     0xffff660c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip      
# https://fontawesome.com/v4/icons/
# Or https://www.nerdfonts.com/font-downloads
#spacebar -m config space_icon_strip     "[1] cube" "[2] globe" "[3] envelope-open" "[4] comment" "[5] music" "(6) paint-brush" "(7) terminal"
spacebar -m config space_icon_strip     " ¹" " ²" " ³" " ⁴" " ⁵" " ⁶"
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%d/%m/%y %R"
spacebar -m config right_shell          on
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "whoami"

spacebar -m config debug_output off

echo "spacebar configuration loaded.."
